apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceName }}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.deploymentName }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.matchLabels| nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels| nindent 8 }}
    spec:
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.deploymentName }}
      containers:
      - image: {{ .Values.deploymentImagerepository }}
        imagePullPolicy: {{ .Values.deploymentImagepullPolicy }}
        name: {{ .Values.deploymentContainer.name }}
        ports:
        - containerPort: {{ .Values.deploymentContainer.targetport }}
        resources:
          limits:
            memory: {{ .Values.deploymentContainer.memory }}
            cpu: {{ .Values.deploymentContainer.cpu }}
        env:
          - name: {{ .Values.secret.credential }}
            valueFrom:
              secretKeyRef:
                name:  {{ .Values.secretName }}
                key: {{ .Values.parameterStore.credentialAlias }}
        