apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.ingressName }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: {{ .Values.ingressRules.host }} 
      http:
        paths:
          - pathType: {{ .Values.ingressRules.type }} 
            path: {{ .Values.ingressRules.path }} 
            backend:
              serviceName: {{ .Values.serviceName }}
              servicePort: {{ .Values.service.port }}