apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Name }}
spec:
  provider: aws
  secretObjects:
    - secretName: {{ .Values.secretName }}
      type: Opaque
      data:
        - objectName: {{ .Values.secret.type }}
          key: {{ .Values.secret.credential }}
  parameters:
    objects: |
        - objectName: {{ .Values.parameterStore.credential }}
          objectType: {{ .Values.parameterStore.type }}
          objectAlias: {{ .Values.parameterStore.credentialAlias }}